//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concordance.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concordance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FillDownHS {
            get {
                object obj = ResourceManager.GetObject("FillDownHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormRunHS {
            get {
                object obj = ResourceManager.GetObject("FormRunHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HTMLPageHS {
            get {
                object obj = ResourceManager.GetObject("HTMLPageHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImportXMLHS {
            get {
                object obj = ResourceManager.GetObject("ImportXMLHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access error.
        /// </summary>
        internal static string MainFormPresenterAccessErrorTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterAccessErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0/0.
        /// </summary>
        internal static string MainFormPresenterClearContextsValue {
            get {
                return ResourceManager.GetString("MainFormPresenterClearContextsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}/{1}.
        /// </summary>
        internal static string MainFormPresenterContextsMask {
            get {
                return ResourceManager.GetString("MainFormPresenterContextsMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export from XML.
        /// </summary>
        internal static string MainFormPresenterExportFileDialogTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterExportFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - {1}.
        /// </summary>
        internal static string MainFormPresenterFormTitleMask {
            get {
                return ResourceManager.GetString("MainFormPresenterFormTitleMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML document|*.xml.
        /// </summary>
        internal static string MainFormPresenterImportExportFileFilter {
            get {
                return ResourceManager.GetString("MainFormPresenterImportExportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import from XML.
        /// </summary>
        internal static string MainFormPresenterImportFileDialogTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterImportFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input/Output error.
        /// </summary>
        internal static string MainFormPresenterIOErrorTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterIOErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        internal static string MainFormPresenterOpenFileDialogTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterOpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plain text|*.txt|All files|*.*.
        /// </summary>
        internal static string MainFormPresenterOpenFileFilter {
            get {
                return ResourceManager.GetString("MainFormPresenterOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan error.
        /// </summary>
        internal static string MainFormPresenterScanErrorTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterScanErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security error.
        /// </summary>
        internal static string MainFormPresenterSecurityErrorTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterSecurityErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consumed time: {0} sec..
        /// </summary>
        internal static string MainFormPresenterStatusMask {
            get {
                return ResourceManager.GetString("MainFormPresenterStatusMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation was completed successfully..
        /// </summary>
        internal static string MainFormPresenterSuccessMessage {
            get {
                return ResourceManager.GetString("MainFormPresenterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        internal static string MainFormPresenterSuccessTitle {
            get {
                return ResourceManager.GetString("MainFormPresenterSuccessTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PlayHS {
            get {
                object obj = ResourceManager.GetObject("PlayHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextboxHS {
            get {
                object obj = ResourceManager.GetObject("TextboxHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XMLFileHS {
            get {
                object obj = ResourceManager.GetObject("XMLFileHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
